version: "3.8"

services:
  api:
    build: ./api
    container_name: fiscalia_api
    ports:
      - "8080:8080"
    env_file:
      - ./api/app/.env
  

  ui:
    build: ./web_ui
    container_name: fiscalia_ui
    ports:
      - "8501:8501"
    depends_on:
      - api
    environment:
      - API_URL=http://api:8080/ask
